### PR TITLE
maintain dark font for code snippets highlighted with yellow background

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**

### CODE REVIEW

**Comment by CharlieEtienne** [comment]
Hi, could you give an example ? A link or at least a screenshot ? 
Thanks!

**Comment by KiaraGrouwstra** [comment]
edit: sure, this is what it looks like for highlighted items in the search without the patch:
image

**Comment by CharlieEtienne** [comment]
thanks @tycho01,

I was about to merge your commit but, thinking of it, I wonder if we shouldn't make background color darker, maybe with `hsla(39, 25%, 30%, 1)` or something close to it, instead of making text color dark.

What do you think ?

If you disagree I'll merge your commit.

**Comment by KiaraGrouwstra** [comment]
edit: just tried your idea as well:
image
looks fine to me :)

**Comment by CharlieEtienne** [comment]
Great, you can commit and I'll merge. 
Thanks @tycho01

**Comment by KiaraGrouwstra** [comment]
edit: I've updated my PR. :)

**Comment by CharlieEtienne** [comment]
style updated on userstyles.org
https://userstyles.org/styles/174317/material-dark-github
thanks !

**Pull request merged**
